// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ljmdbrunpuhnnmouuuzg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxqbWRicnVucHVobm5tb3V1dXpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MzgwMDYsImV4cCI6MjA2NDUxNDAwNn0.cDCB1XcMBPQceZGrxZtwerhxCYb3-rdYgEFlYW6Ie78";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);